2025-07-24 16:15:04,420 p=89427 u=hal n=ansible WARNING| [WARNING]: Error in vault password file loading (default): Could not read vault
password file /home/bill/.vault_pass.txt: [Errno 13] Permission denied:
'/home/bill/.vault_pass.txt'

2025-07-24 16:15:04,421 p=89427 u=hal n=ansible ERROR| ERROR! Could not read vault password file /home/bill/.vault_pass.txt: [Errno 13] Permission denied: '/home/bill/.vault_pass.txt'
2025-07-24 16:24:49,535 p=89964 u=bill n=ansible WARNING| [WARNING]: Found both group and host with same name: truenas

2025-07-24 16:24:49,690 p=89964 u=bill n=ansible INFO| bazarr | UNREACHABLE! => {
    "changed": false,
    "msg": "Data could not be sent to remote host \"192.168.86.76\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.76 port 22: Connection refused\r\n",
    "unreachable": true
}
2025-07-24 16:26:18,242 p=90275 u=bill n=ansible INFO| ansible [core 2.18.7]
  config file = /home/bill/git/home.net/ansible.cfg
  configured module search path = ['/home/bill/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/bill/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Jun 18 2025, 17:59:45) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
2025-07-24 16:26:18,242 p=90275 u=bill n=ansible INFO| Using /home/bill/git/home.net/ansible.cfg as config file
2025-07-24 16:26:18,329 p=90275 u=bill n=ansible WARNING| [WARNING]: Found both group and host with same name: truenas

2025-07-24 16:26:18,362 p=90275 u=bill n=ansible INFO| Skipping callback 'default', as we already have a stdout callback.
2025-07-24 16:26:18,362 p=90275 u=bill n=ansible INFO| Skipping callback 'minimal', as we already have a stdout callback.
2025-07-24 16:26:18,362 p=90275 u=bill n=ansible INFO| Skipping callback 'oneline', as we already have a stdout callback.
2025-07-24 16:26:18,489 p=90275 u=bill n=ansible INFO| bazarr | UNREACHABLE! => {
    "changed": false,
    "msg": "Data could not be sent to remote host \"192.168.86.76\". Make sure this host can be reached over ssh: OpenSSH_9.6p1 Ubuntu-3ubuntu13.13, OpenSSL 3.0.13 30 Jan 2024\r\ndebug1: Reading configuration data /home/bill/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.86.76 is address\r\ndebug1: auto-mux: Trying existing master at '/home/bill/.ansible/cp/192.168.86.76-hal'\r\ndebug1: Control socket \"/home/bill/.ansible/cp/192.168.86.76-hal\" does not exist\r\ndebug1: Connecting to 192.168.86.76 [192.168.86.76] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 192.168.86.76 port 22: Connection refused\r\nssh: connect to host 192.168.86.76 port 22: Connection refused\r\n",
    "unreachable": true
}
2025-07-24 16:26:30,904 p=90320 u=bill n=ansible INFO| ansible [core 2.18.7]
  config file = /home/bill/git/home.net/ansible.cfg
  configured module search path = ['/home/bill/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/bill/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Jun 18 2025, 17:59:45) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
2025-07-24 16:26:30,904 p=90320 u=bill n=ansible INFO| Using /home/bill/git/home.net/ansible.cfg as config file
2025-07-24 16:26:30,989 p=90320 u=bill n=ansible INFO| Parsed /home/bill/git/home.net/inventory inventory source with ini plugin
2025-07-24 16:26:30,989 p=90320 u=bill n=ansible WARNING| [WARNING]: Found both group and host with same name: truenas

2025-07-24 16:26:31,023 p=90320 u=bill n=ansible INFO| Skipping callback 'default', as we already have a stdout callback.
2025-07-24 16:26:31,023 p=90320 u=bill n=ansible INFO| Skipping callback 'minimal', as we already have a stdout callback.
2025-07-24 16:26:31,023 p=90320 u=bill n=ansible INFO| Skipping callback 'oneline', as we already have a stdout callback.
2025-07-24 16:26:31,140 p=90320 u=bill n=ansible INFO| Using module file /usr/lib/python3/dist-packages/ansible/modules/ping.py
2025-07-24 16:26:31,141 p=90320 u=bill n=ansible INFO| Pipelining is enabled.
2025-07-24 16:26:31,141 p=90320 u=bill n=ansible INFO| <192.168.86.76> ESTABLISH SSH CONNECTION FOR USER: hal
2025-07-24 16:26:31,141 p=90320 u=bill n=ansible INFO| <192.168.86.76> SSH: EXEC ssh -vvv -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/bill/.ssh/ansible-server"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="hal"' -o ConnectTimeout=10 -o 'ControlPath="/home/bill/.ansible/cp/%h-%r"' 192.168.86.76 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-qihnqiktrcnsaivphskqytkgijdvrmit ; /usr/bin/python3'"'"'"'"'"'"'"'"' && sleep 0'"'"''
2025-07-24 16:26:31,147 p=90320 u=bill n=ansible INFO| bazarr | UNREACHABLE! => {
    "changed": false,
    "msg": "Data could not be sent to remote host \"192.168.86.76\". Make sure this host can be reached over ssh: OpenSSH_9.6p1 Ubuntu-3ubuntu13.13, OpenSSL 3.0.13 30 Jan 2024\r\ndebug1: Reading configuration data /home/bill/.ssh/config\r\ndebug3: kex names ok: [diffie-hellman-group14-sha256]\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.86.76 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/bill/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/bill/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master at '/home/bill/.ansible/cp/192.168.86.76-hal'\r\ndebug1: Control socket \"/home/bill/.ansible/cp/192.168.86.76-hal\" does not exist\r\ndebug3: channel_clear_timeouts: clearing\r\ndebug3: ssh_connect_direct: entering\r\ndebug1: Connecting to 192.168.86.76 [192.168.86.76] port 22.\r\ndebug3: set_sock_tos: set socket 3 IP_TOS 0x10\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 192.168.86.76 port 22: Connection refused\r\nssh: connect to host 192.168.86.76 port 22: Connection refused\r\n",
    "unreachable": true
}
2025-07-24 16:28:31,527 p=90545 u=bill n=ansible WARNING| [WARNING]: Found both group and host with same name: truenas

2025-07-24 16:28:32,874 p=90545 u=bill n=ansible INFO| pve | CHANGED | rc=0 >>
status: running

2025-07-24 16:28:44,567 p=90594 u=bill n=ansible WARNING| [WARNING]: Found both group and host with same name: truenas

2025-07-24 16:28:45,658 p=90594 u=bill n=ansible INFO| pve | FAILED | rc=3 >>
Ã— ssh.service - OpenBSD Secure Shell server
     Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2025-07-24 16:01:13 EDT; 27min ago
       Docs: man:sshd(8)
             man:sshd_config(5)
    Process: 353 ExecStartPre=/usr/sbin/sshd -t (code=exited, status=0/SUCCESS)
    Process: 380 ExecStart=/usr/sbin/sshd -D $SSHD_OPTS (code=exited, status=255/EXCEPTION)
   Main PID: 380 (code=exited, status=255/EXCEPTION)
        CPU: 18ms

Jul 24 16:01:13 bazarr systemd[1]: Starting OpenBSD Secure Shell server...
Jul 24 16:01:13 bazarr sshd[380]: error: Bind to port 22 on 0.0.0.0 failed: Address already in use.
Jul 24 16:01:13 bazarr sshd[380]: error: Bind to port 22 on :: failed: Address already in use.
Jul 24 16:01:13 bazarr sshd[380]: fatal: Cannot bind any address.
Jul 24 16:01:13 bazarr systemd[1]: ssh.service: Main process exited, code=exited, status=255/EXCEPTION
Jul 24 16:01:13 bazarr systemd[1]: ssh.service: Failed with result 'exit-code'.
Jul 24 16:01:13 bazarr systemd[1]: Failed to start OpenBSD Secure Shell server.non-zero return code

2025-07-24 16:28:53,890 p=90640 u=bill n=ansible WARNING| [WARNING]: Found both group and host with same name: truenas

2025-07-24 16:28:54,772 p=90640 u=bill n=ansible INFO| pve | FAILED | rc=1 >>
non-zero return code

2025-07-24 16:29:01,670 p=90680 u=bill n=ansible WARNING| [WARNING]: Found both group and host with same name: truenas

2025-07-24 16:29:02,555 p=90680 u=bill n=ansible INFO| pve | FAILED | rc=1 >>
non-zero return code

2025-07-24 16:29:13,221 p=90722 u=bill n=ansible WARNING| [WARNING]: Found both group and host with same name: truenas

2025-07-24 16:29:22,919 p=90722 u=bill n=ansible INFO| pve | CHANGED | rc=0 >>


2025-07-24 16:29:45,807 p=90836 u=bill n=ansible WARNING| [WARNING]: Found both group and host with same name: truenas

2025-07-24 16:29:46,414 p=90836 u=bill n=ansible INFO| bazarr | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
2025-07-24 16:30:44,866 p=91157 u=bill n=ansible WARNING| [WARNING]: Found both group and host with same name: truenas

2025-07-24 16:30:45,133 p=91157 u=bill n=ansible INFO| bazarr | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
