2025-07-16 21:26:57,081 p=80946 u=bill n=ansible INFO| prowlarr | UNREACHABLE! => {
2025-07-16 21:26:57,089 p=80946 u=bill n=ansible INFO| samsung | UNREACHABLE! => {
2025-07-16 21:26:57,103 p=80946 u=bill n=ansible INFO| desktop | UNREACHABLE! => {
2025-07-16 21:27:06,618 p=80946 u=bill n=ansible INFO| lily_laptop | UNREACHABLE! => {
2025-07-16 21:27:12,320 p=80946 u=bill n=ansible INFO| homeassistant | UNREACHABLE! => {
2025-07-17 16:27:30,109 p=95679 u=bill n=ansible INFO| fatal: [prowlarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.123\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.123 port 22: No route to host\r\n", "unreachable": true}
2025-07-17 16:27:30,120 p=95679 u=bill n=ansible INFO| fatal: [samsung]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.94\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.94 port 22: No route to host\r\n", "unreachable": true}
2025-07-17 16:27:31,065 p=95679 u=bill n=ansible INFO| fatal: [dell]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.55\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.55 port 22: No route to host\r\n", "unreachable": true}
2025-07-17 16:27:34,829 p=95679 u=bill n=ansible INFO| fatal: [homeassistant]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@192.168.86.51: Permission denied (publickey).", "unreachable": true}
2025-07-17 16:27:35,477 p=95679 u=bill n=ansible INFO| fatal: [lily_laptop]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.53\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.53 port 22: No route to host\r\n", "unreachable": true}
2025-07-17 16:28:02,579 p=95679 u=bill n=ansible INFO| fatal: [truenas]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/apt-get update", "msg": "", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "Package management tools are disabled on TrueNAS appliances.\n\nAttempting to update TrueNAS with apt or methods other than the TrueNAS web\ninterface can result in a nonfunctional system.\n", "stdout_lines": ["Package management tools are disabled on TrueNAS appliances.", "", "Attempting to update TrueNAS with apt or methods other than the TrueNAS web", "interface can result in a nonfunctional system."]}
2025-07-17 16:29:40,238 p=95679 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'str object' has no attribute 'home'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create user home directories\n  ^ here\n"}
2025-07-17 16:29:41,107 p=95679 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create NFS symlinks for lily\n  ^ here\n"}
2025-07-17 16:29:41,137 p=95679 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 51, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create local directories for lily\n  ^ here\n"}
2025-07-17 16:29:41,167 p=95679 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 62, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create NFS symlinks for loretta\n  ^ here\n"}
2025-07-17 16:29:41,197 p=95679 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 74, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create local directories for loretta\n  ^ here\n"}
2025-07-17 16:30:23,021 p=95679 u=bill n=ansible INFO| fatal: [bazarr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "checksum": "7af7046de097916e441333aecd5b6e9630e00f16", "msg": "Failed to replace file: b'/home/hal/.ansible/tmp/ansible-tmp-1752784222.4171808-102974-82386215158545/.source.conf' to /etc/pve/lxc/118.conf: [Errno 1] Operation not permitted: b'/etc/pve/lxc/.ansible_tmp0fntur54118.conf'"}
2025-07-17 16:30:23,482 p=95679 u=bill n=ansible INFO| fatal: [books -> pve(192.168.86.143)]: FAILED! => {"changed": false, "checksum": "482de401a19519f4e4bb7ae36d2c34a204625fdd", "msg": "Failed to replace file: b'/home/hal/.ansible/tmp/ansible-tmp-1752784223.0574865-103025-166602690606514/.source.conf' to /etc/pve/lxc/126.conf: [Errno 1] Operation not permitted: b'/etc/pve/lxc/.ansible_tmpu6981nez126.conf'"}
2025-07-17 16:30:23,680 p=95679 u=bill n=ansible INFO| fatal: [ntfy -> pve(192.168.86.143)]: FAILED! => {"changed": false, "checksum": "a89b2dba9db973e0ee3ebb710a8e4b57c29099c8", "msg": "Failed to replace file: b'/home/hal/.ansible/tmp/ansible-tmp-1752784223.1926847-103032-267512588760168/.source.conf' to /etc/pve/lxc/130.conf: [Errno 1] Operation not permitted: b'/etc/pve/lxc/.ansible_tmpel7r5p41130.conf'"}
2025-07-17 16:30:24,108 p=95679 u=bill n=ansible INFO| fatal: [tautulli -> pve(192.168.86.143)]: FAILED! => {"changed": false, "checksum": "d4797d1a918068caa748f8f1529f71871d4154e4", "msg": "Failed to replace file: b'/home/hal/.ansible/tmp/ansible-tmp-1752784223.6966014-103072-78689918080770/.source.conf' to /etc/pve/lxc/129.conf: [Errno 1] Operation not permitted: b'/etc/pve/lxc/.ansible_tmp36dbu86e129.conf'"}
2025-07-17 16:30:25,323 p=95679 u=bill n=ansible INFO| fatal: [bazarr -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 118 && sleep 5 && pct start 118", "delta": "0:00:00.631257", "end": "2025-07-17 16:30:25.294926", "msg": "non-zero return code", "rc": 255, "start": "2025-07-17 16:30:24.663669", "stderr": "CT 118 not running", "stderr_lines": ["CT 118 not running"], "stdout": "", "stdout_lines": []}
2025-07-17 16:30:33,033 p=95679 u=bill n=ansible INFO| fatal: [sonarr -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 107 && sleep 5 && pct start 107", "delta": "0:00:08.270324", "end": "2025-07-17 16:30:33.008354", "msg": "non-zero return code", "rc": 255, "start": "2025-07-17 16:30:24.738030", "stderr": "no such logical volume pve/vm-107-disk-0", "stderr_lines": ["no such logical volume pve/vm-107-disk-0"], "stdout": "", "stdout_lines": []}
2025-07-17 16:30:33,722 p=95679 u=bill n=ansible INFO| fatal: [paperless -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 111 && sleep 5 && pct start 111", "delta": "0:00:08.205920", "end": "2025-07-17 16:30:33.697079", "msg": "non-zero return code", "rc": 255, "start": "2025-07-17 16:30:25.491159", "stderr": "no such logical volume pve/vm-111-disk-0", "stderr_lines": ["no such logical volume pve/vm-111-disk-0"], "stdout": "", "stdout_lines": []}
2025-07-17 16:30:33,847 p=95679 u=bill n=ansible INFO| fatal: [books -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 126 && sleep 5 && pct start 126", "delta": "0:00:00.613874", "end": "2025-07-17 16:30:33.821016", "msg": "non-zero return code", "rc": 255, "start": "2025-07-17 16:30:33.207142", "stderr": "CT 126 not running", "stderr_lines": ["CT 126 not running"], "stdout": "", "stdout_lines": []}
2025-07-17 16:30:35,433 p=95679 u=bill n=ansible INFO| fatal: [ntfy -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 130 && sleep 5 && pct start 130", "delta": "0:00:00.752839", "end": "2025-07-17 16:30:35.405907", "msg": "non-zero return code", "rc": 255, "start": "2025-07-17 16:30:34.653068", "stderr": "CT 130 not running", "stderr_lines": ["CT 130 not running"], "stdout": "", "stdout_lines": []}
2025-07-17 16:30:36,315 p=95679 u=bill n=ansible INFO| fatal: [tautulli -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 129 && sleep 5 && pct start 129", "delta": "0:00:00.655388", "end": "2025-07-17 16:30:36.291180", "msg": "non-zero return code", "rc": 255, "start": "2025-07-17 16:30:35.635792", "stderr": "CT 129 not running", "stderr_lines": ["CT 129 not running"], "stdout": "", "stdout_lines": []}
2025-07-17 16:30:42,237 p=95679 u=bill n=ansible INFO| fatal: [overseer -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 106 && sleep 5 && pct start 106", "delta": "0:00:08.327830", "end": "2025-07-17 16:30:42.214695", "msg": "non-zero return code", "rc": 255, "start": "2025-07-17 16:30:33.886865", "stderr": "no such logical volume pve/vm-106-disk-0", "stderr_lines": ["no such logical volume pve/vm-106-disk-0"], "stdout": "", "stdout_lines": []}
2025-07-17 16:30:42,362 p=95679 u=bill n=ansible INFO| fatal: [radarr -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 106 && sleep 5 && pct start 106", "delta": "0:00:08.307004", "end": "2025-07-17 16:30:42.338984", "msg": "non-zero return code", "rc": 255, "start": "2025-07-17 16:30:34.031980", "stderr": "no such logical volume pve/vm-106-disk-0", "stderr_lines": ["no such logical volume pve/vm-106-disk-0"], "stdout": "trying to acquire lock...\n OK\ntrying to acquire lock...\n OK", "stdout_lines": ["trying to acquire lock...", " OK", "trying to acquire lock...", " OK"]}
2025-07-17 16:30:43,111 p=95679 u=bill n=ansible INFO| fatal: [homepage -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 107 && sleep 5 && pct start 107", "delta": "0:00:00.634612", "end": "2025-07-17 16:30:43.092370", "msg": "non-zero return code", "rc": 255, "start": "2025-07-17 16:30:42.457758", "stderr": "CT 107 not running", "stderr_lines": ["CT 107 not running"], "stdout": "", "stdout_lines": []}
2025-07-17 16:30:43,333 p=95679 u=bill n=ansible INFO| fatal: [sab -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 116 && sleep 5 && pct start 116", "delta": "0:00:08.423773", "end": "2025-07-17 16:30:43.314649", "msg": "non-zero return code", "rc": 255, "start": "2025-07-17 16:30:34.890876", "stderr": "no such logical volume pve/vm-116-disk-0", "stderr_lines": ["no such logical volume pve/vm-116-disk-0"], "stdout": "", "stdout_lines": []}
2025-07-17 16:30:43,377 p=95679 u=bill n=ansible INFO| fatal: [maintainerr -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 112 && sleep 5 && pct start 112", "delta": "0:00:08.607299", "end": "2025-07-17 16:30:43.361203", "msg": "non-zero return code", "rc": 255, "start": "2025-07-17 16:30:34.753904", "stderr": "no such logical volume pve/vm-112-disk-0", "stderr_lines": ["no such logical volume pve/vm-112-disk-0"], "stdout": "", "stdout_lines": []}
2025-07-17 16:30:44,568 p=95679 u=bill n=ansible INFO| fatal: [cloudflared -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 113 && sleep 5 && pct start 113", "delta": "0:00:08.081286", "end": "2025-07-17 16:30:44.549269", "msg": "non-zero return code", "rc": 255, "start": "2025-07-17 16:30:36.467983", "stderr": "no such logical volume pve/vm-113-disk-0", "stderr_lines": ["no such logical volume pve/vm-113-disk-0"], "stdout": "", "stdout_lines": []}
2025-07-17 16:30:50,641 p=95679 u=bill n=ansible INFO| fatal: [calibre-web -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 109 && sleep 5 && pct start 109", "delta": "0:00:08.048967", "end": "2025-07-17 16:30:50.626351", "msg": "non-zero return code", "rc": 255, "start": "2025-07-17 16:30:42.577384", "stderr": "no such logical volume pve/vm-109-disk-0", "stderr_lines": ["no such logical volume pve/vm-109-disk-0"], "stdout": "", "stdout_lines": []}
2025-07-17 16:30:51,278 p=95679 u=bill n=ansible INFO| fatal: [photoprism]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.95\". Make sure this host can be reached over ssh: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\n@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\nIT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!\r\nSomeone could be eavesdropping on you right now (man-in-the-middle attack)!\r\nIt is also possible that a host key has just been changed.\r\nThe fingerprint for the ED25519 key sent by the remote host is\nSHA256:sYEgk0PDyFN2g9Aso34gqlFDuWYHVCpoiR+znlFVbzM.\r\nPlease contact your system administrator.\r\nAdd correct host key in /home/bill/.ssh/known_hosts to get rid of this message.\r\nOffending ED25519 key in /home/bill/.ssh/known_hosts:59\r\n  remove with:\r\n  ssh-keygen -f '/home/bill/.ssh/known_hosts' -R '192.168.86.95'\r\nAgent forwarding is disabled to avoid man-in-the-middle attacks.\r\nUpdateHostkeys is disabled because the host key is not trusted.\r\nUse of this system is private. If you are not authorized, disconnect immediately.\nFailure to comply will result in your destruction.hal@192.168.86.95: Permission denied (publickey).\r\n", "unreachable": true}
2025-07-17 16:31:01,098 p=95679 u=bill n=ansible INFO| fatal: [wg]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.104\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.104 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-17 16:31:01,125 p=95679 u=bill n=ansible INFO| fatal: [bazarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.76\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.76 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-17 16:31:01,143 p=95679 u=bill n=ansible INFO| fatal: [trilium]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.78\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.78 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-17 16:31:01,163 p=95679 u=bill n=ansible INFO| fatal: [sonarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.66\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.66 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-17 16:31:01,303 p=95679 u=bill n=ansible INFO| fatal: [paperless]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.96\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.96 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-17 16:31:11,124 p=95679 u=bill n=ansible INFO| fatal: [books]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.70\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.70 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-17 16:31:11,166 p=95679 u=bill n=ansible INFO| fatal: [radarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.79\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.79 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-17 16:31:11,190 p=95679 u=bill n=ansible INFO| fatal: [ntfy]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.97\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.97 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-17 16:31:11,927 p=95679 u=bill n=ansible INFO| fatal: [sab]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.86\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.86 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-17 16:33:02,858 p=95679 u=bill n=ansible INFO| fatal: [windows11]: FAILED! => {"msg": "The field 'password' has an invalid value, which includes an undefined variable.. 'windows_password' is undefined"}
2025-07-18 14:31:23,735 p=111864 u=bill n=ansible INFO| fatal: [photoprism -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/103.conf to /etc/pve/lxc/103.conf.backup.1752863482", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_p_8qzbn5/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_p_8qzbn5/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/103.conf.backup.1752863482'\n"}
2025-07-18 14:35:02,176 p=112016 u=bill n=ansible INFO| fatal: [photoprism -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "file not found: /tmp/103_desired.conf"}
2025-07-18 14:35:02,206 p=112016 u=bill n=ansible INFO| fatal: [photoprism]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'dict object' has no attribute 'content'\n\nThe error appears to be in '/home/bill/git/home.net/roles/lxc/tasks/lxc_mounts_idempotent.yml': line 58, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Extract current mount points and user mappings\n  ^ here\n"}
2025-07-18 14:35:02,230 p=112016 u=bill n=ansible INFO| fatal: [photoprism]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'current_mounts' is undefined\n\nThe error appears to be in '/home/bill/git/home.net/roles/lxc/tasks/lxc_mounts_idempotent.yml': line 66, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Determine if configuration needs updating\n  ^ here\n"}
2025-07-18 14:35:02,255 p=112016 u=bill n=ansible INFO| fatal: [photoprism]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'current_mounts' is undefined\n\nThe error appears to be in '/home/bill/git/home.net/roles/lxc/tasks/lxc_mounts_idempotent.yml': line 76, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Display current vs desired state\n  ^ here\n"}
2025-07-18 14:36:50,806 p=112186 u=bill n=ansible INFO| fatal: [photoprism -> pve]: FAILED! => {"msg": "The conditional check 'config_updated is succeeded' failed. The error was: The 'failed' test expects a dictionary\n\nThe error appears to be in '/home/bill/git/home.net/roles/lxc/tasks/lxc_mounts_safe.yml': line 90, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Restart container if it was running (to apply mount/idmap changes)\n  ^ here\n"}
2025-07-18 14:40:25,340 p=112904 u=bill n=ansible INFO| fatal: [prowlarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.123\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.123 port 22: No route to host\r\n", "unreachable": true}
2025-07-18 14:40:25,352 p=112904 u=bill n=ansible INFO| fatal: [samsung]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.94\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.94 port 22: No route to host\r\n", "unreachable": true}
2025-07-18 14:40:26,300 p=112904 u=bill n=ansible INFO| fatal: [dell]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.55\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.55 port 22: No route to host\r\n", "unreachable": true}
2025-07-18 14:40:26,588 p=112904 u=bill n=ansible INFO| fatal: [maintainerr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.65\". Make sure this host can be reached over ssh: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\n@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\nIT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!\r\nSomeone could be eavesdropping on you right now (man-in-the-middle attack)!\r\nIt is also possible that a host key has just been changed.\r\nThe fingerprint for the ED25519 key sent by the remote host is\nSHA256:U1zJq/odIZDuR6itrbQYSul32AUl2r4DmB+7nesWJEY.\r\nPlease contact your system administrator.\r\nAdd correct host key in /home/bill/.ssh/known_hosts to get rid of this message.\r\nOffending ED25519 key in /home/bill/.ssh/known_hosts:21\r\n  remove with:\r\n  ssh-keygen -f '/home/bill/.ssh/known_hosts' -R '192.168.86.65'\r\nAgent forwarding is disabled to avoid man-in-the-middle attacks.\r\nUpdateHostkeys is disabled because the host key is not trusted.\r\nUse of this system is private. If you are not authorized, disconnect immediately.\nFailure to comply will result in your destruction.hal@192.168.86.65: Permission denied (publickey).\r\n", "unreachable": true}
2025-07-18 14:40:28,494 p=112904 u=bill n=ansible INFO| fatal: [homeassistant]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@192.168.86.51: Permission denied (publickey).", "unreachable": true}
2025-07-18 14:40:30,581 p=112904 u=bill n=ansible INFO| fatal: [lily_laptop]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.53\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.53 port 22: No route to host\r\n", "unreachable": true}
2025-07-18 14:40:53,435 p=112904 u=bill n=ansible INFO| fatal: [truenas]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/apt-get update", "msg": "", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "Package management tools are disabled on TrueNAS appliances.\n\nAttempting to update TrueNAS with apt or methods other than the TrueNAS web\ninterface can result in a nonfunctional system.\n", "stdout_lines": ["Package management tools are disabled on TrueNAS appliances.", "", "Attempting to update TrueNAS with apt or methods other than the TrueNAS web", "interface can result in a nonfunctional system."]}
2025-07-18 14:42:26,395 p=112904 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'str object' has no attribute 'home'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create user home directories\n  ^ here\n"}
2025-07-18 14:42:27,240 p=112904 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create NFS symlinks for lily\n  ^ here\n"}
2025-07-18 14:42:27,271 p=112904 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 51, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create local directories for lily\n  ^ here\n"}
2025-07-18 14:42:27,301 p=112904 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 62, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create NFS symlinks for loretta\n  ^ here\n"}
2025-07-18 14:42:27,332 p=112904 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 74, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create local directories for loretta\n  ^ here\n"}
2025-07-18 14:43:10,268 p=112904 u=bill n=ansible INFO| fatal: [wg -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/101.conf to /etc/pve/lxc/101.conf.backup.1752864184", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_0n70um48/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_0n70um48/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/101.conf.backup.1752864184'\n"}
2025-07-18 14:43:10,316 p=112904 u=bill n=ansible INFO| fatal: [photoprism -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/103.conf to /etc/pve/lxc/103.conf.backup.1752864184", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_gn3ai8wq/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_gn3ai8wq/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/103.conf.backup.1752864184'\n"}
2025-07-18 14:43:10,374 p=112904 u=bill n=ansible INFO| fatal: [trilium -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/104.conf to /etc/pve/lxc/104.conf.backup.1752864184", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_hxl69upf/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_hxl69upf/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/104.conf.backup.1752864184'\n"}
2025-07-18 14:43:10,414 p=112904 u=bill n=ansible INFO| fatal: [sonarr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/107.conf to /etc/pve/lxc/107.conf.backup.1752864184", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_c2l2liga/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_c2l2liga/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/107.conf.backup.1752864184'\n"}
2025-07-18 14:43:10,461 p=112904 u=bill n=ansible INFO| fatal: [paperless -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/111.conf to /etc/pve/lxc/111.conf.backup.1752864184", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_km0irq4u/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_km0irq4u/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/111.conf.backup.1752864184'\n"}
2025-07-18 14:43:10,566 p=112904 u=bill n=ansible INFO| fatal: [overseer -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/106.conf to /etc/pve/lxc/106.conf.backup.1752864185", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_814jbh2m/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_814jbh2m/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/106.conf.backup.1752864185'\n"}
2025-07-18 14:43:10,676 p=112904 u=bill n=ansible INFO| fatal: [sab -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/116.conf to /etc/pve/lxc/116.conf.backup.1752864185", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_e9s364q3/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_e9s364q3/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/116.conf.backup.1752864185'\n"}
2025-07-18 14:43:10,758 p=112904 u=bill n=ansible INFO| fatal: [cloudflared -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/113.conf to /etc/pve/lxc/113.conf.backup.1752864185", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_yqomyyai/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_yqomyyai/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/113.conf.backup.1752864185'\n"}
2025-07-18 14:43:10,764 p=112904 u=bill n=ansible INFO| fatal: [homepage -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/107.conf to /etc/pve/lxc/107.conf.backup.1752864185", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload__9go7n53/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload__9go7n53/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/107.conf.backup.1752864185'\n"}
2025-07-18 14:43:10,796 p=112904 u=bill n=ansible INFO| fatal: [calibre-web -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/109.conf to /etc/pve/lxc/109.conf.backup.1752864186", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_43n73y0q/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_43n73y0q/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/109.conf.backup.1752864186'\n"}
2025-07-18 14:43:16,296 p=112904 u=bill n=ansible INFO| fatal: [bazarr -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct status 118", "delta": "0:00:00.621562", "end": "2025-07-18 14:43:16.266540", "msg": "non-zero return code", "rc": 2, "start": "2025-07-18 14:43:15.644978", "stderr": "Configuration file 'nodes/pve/lxc/118.conf' does not exist", "stderr_lines": ["Configuration file 'nodes/pve/lxc/118.conf' does not exist"], "stdout": "", "stdout_lines": []}
2025-07-18 14:43:17,224 p=112904 u=bill n=ansible INFO| fatal: [books -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct status 126", "delta": "0:00:00.603794", "end": "2025-07-18 14:43:17.194298", "msg": "non-zero return code", "rc": 2, "start": "2025-07-18 14:43:16.590504", "stderr": "Configuration file 'nodes/pve/lxc/126.conf' does not exist", "stderr_lines": ["Configuration file 'nodes/pve/lxc/126.conf' does not exist"], "stdout": "", "stdout_lines": []}
2025-07-18 14:43:17,357 p=112904 u=bill n=ansible INFO| fatal: [ntfy -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct status 130", "delta": "0:00:00.620050", "end": "2025-07-18 14:43:17.325804", "msg": "non-zero return code", "rc": 2, "start": "2025-07-18 14:43:16.705754", "stderr": "Configuration file 'nodes/pve/lxc/130.conf' does not exist", "stderr_lines": ["Configuration file 'nodes/pve/lxc/130.conf' does not exist"], "stdout": "", "stdout_lines": []}
2025-07-18 14:43:18,038 p=112904 u=bill n=ansible INFO| fatal: [tautulli -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct status 129", "delta": "0:00:00.613100", "end": "2025-07-18 14:43:18.020891", "msg": "non-zero return code", "rc": 2, "start": "2025-07-18 14:43:17.407791", "stderr": "Configuration file 'nodes/pve/lxc/129.conf' does not exist", "stderr_lines": ["Configuration file 'nodes/pve/lxc/129.conf' does not exist"], "stdout": "", "stdout_lines": []}
2025-07-18 14:43:25,622 p=112904 u=bill n=ansible INFO| fatal: [paperless -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 111 && sleep 3 && pct start 111", "delta": "0:00:07.016757", "end": "2025-07-18 14:43:25.587603", "msg": "non-zero return code", "rc": 255, "start": "2025-07-18 14:43:18.570846", "stderr": "startup for container '111' failed", "stderr_lines": ["startup for container '111' failed"], "stdout": "run_buffer: 571 Script exited with status 2\nlxc_init: 845 Failed to run lxc.hook.pre-start for container \"111\"\n__lxc_start: 2034 Failed to initialize container \"111\"", "stdout_lines": ["run_buffer: 571 Script exited with status 2", "lxc_init: 845 Failed to run lxc.hook.pre-start for container \"111\"", "__lxc_start: 2034 Failed to initialize container \"111\""]}
2025-07-18 14:43:33,592 p=112904 u=bill n=ansible INFO| fatal: [overseer -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 106 && sleep 3 && pct start 106", "delta": "0:00:07.586804", "end": "2025-07-18 14:43:33.559686", "msg": "non-zero return code", "rc": 255, "start": "2025-07-18 14:43:25.972882", "stderr": "trying to acquire lock...\n OK\nstartup for container '106' failed", "stderr_lines": ["trying to acquire lock...", " OK", "startup for container '106' failed"], "stdout": "lxc.idmap: invalid map entry 'u 0 100000 1000': container uid 0 is also mapped by entry 'u 0 100000 1000'\nlxc_map_ids: 245 newuidmap failed to write mapping \"newuidmap: write to uid_map failed: Invalid argument\": newuidmap 4138567 0 100000 1000 1000 1000 1000 2000 101000 64536 0 100000 1000 1000 1000 1000 2000 101000 64536\nlxc_spawn: 1795 Failed to set up id mapping.", "stdout_lines": ["lxc.idmap: invalid map entry 'u 0 100000 1000': container uid 0 is also mapped by entry 'u 0 100000 1000'", "lxc_map_ids: 245 newuidmap failed to write mapping \"newuidmap: write to uid_map failed: Invalid argument\": newuidmap 4138567 0 100000 1000 1000 1000 1000 2000 101000 64536 0 100000 1000 1000 1000 1000 2000 101000 64536", "lxc_spawn: 1795 Failed to set up id mapping."]}
2025-07-18 14:43:33,872 p=112904 u=bill n=ansible INFO| fatal: [radarr -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 106 && sleep 3 && pct start 106", "delta": "0:00:07.206852", "end": "2025-07-18 14:43:33.853319", "msg": "non-zero return code", "rc": 255, "start": "2025-07-18 14:43:26.646467", "stderr": "startup for container '106' failed", "stderr_lines": ["startup for container '106' failed"], "stdout": "trying to acquire lock...\n OK\ntrying to acquire lock...\n OK\nlxc.idmap: invalid map entry 'u 0 100000 1000': container uid 0 is also mapped by entry 'u 0 100000 1000'", "stdout_lines": ["trying to acquire lock...", " OK", "trying to acquire lock...", " OK", "lxc.idmap: invalid map entry 'u 0 100000 1000': container uid 0 is also mapped by entry 'u 0 100000 1000'"]}
2025-07-18 14:43:42,739 p=112904 u=bill n=ansible INFO| fatal: [wg]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.104\". Make sure this host can be reached over ssh: Use of this system is private. If you are not authorized, disconnect immediately.\nFailure to comply will result in your destruction.hal@192.168.86.104: Permission denied (publickey).\r\n", "unreachable": true}
2025-07-18 14:43:42,860 p=112904 u=bill n=ansible INFO| fatal: [sonarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.66\". Make sure this host can be reached over ssh: Use of this system is private. If you are not authorized, disconnect immediately.\nFailure to comply will result in your destruction.hal@192.168.86.66: Permission denied (publickey).\r\n", "unreachable": true}
2025-07-18 14:43:52,513 p=112904 u=bill n=ansible INFO| fatal: [bazarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.76\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.76 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-18 14:43:53,898 p=112904 u=bill n=ansible INFO| fatal: [radarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.79\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.79 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-18 14:44:27,382 p=112904 u=bill n=ansible INFO| fatal: [windows11]: FAILED! => {"msg": "The field 'password' has an invalid value, which includes an undefined variable.. 'windows_password' is undefined"}
2025-07-18 14:47:22,933 p=121487 u=bill n=ansible INFO| fatal: [radarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.79\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.79 port 22: No route to host\r\n", "unreachable": true}
2025-07-18 14:51:27,202 p=121980 u=bill n=ansible INFO| fatal: [paperless -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/112.conf to /etc/pve/lxc/112.conf.backup.1752864684", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_jq890k_q/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_jq890k_q/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/112.conf.backup.1752864684'\n"}
2025-07-18 14:51:27,205 p=121980 u=bill n=ansible INFO| fatal: [homepage -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/114.conf to /etc/pve/lxc/114.conf.backup.1752864684", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_s8yb20pz/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_s8yb20pz/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/114.conf.backup.1752864684'\n"}
2025-07-18 14:51:27,208 p=121980 u=bill n=ansible INFO| fatal: [overseer -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/105.conf to /etc/pve/lxc/105.conf.backup.1752864684", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_n8du0o34/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_n8du0o34/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/105.conf.backup.1752864684'\n"}
2025-07-18 14:51:29,412 p=121980 u=bill n=ansible INFO| fatal: [bazarr -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct status 118", "delta": "0:00:00.585376", "end": "2025-07-18 14:51:29.392420", "msg": "non-zero return code", "rc": 2, "start": "2025-07-18 14:51:28.807044", "stderr": "Configuration file 'nodes/pve/lxc/118.conf' does not exist", "stderr_lines": ["Configuration file 'nodes/pve/lxc/118.conf' does not exist"], "stdout": "", "stdout_lines": []}
2025-07-18 14:51:36,520 p=121980 u=bill n=ansible INFO| fatal: [paperless -> pve(192.168.86.143)]: FAILED! => {"changed": true, "cmd": "pct stop 112 && sleep 3 && pct start 112", "delta": "0:00:06.829960", "end": "2025-07-18 14:51:36.501877", "msg": "non-zero return code", "rc": 255, "start": "2025-07-18 14:51:29.671917", "stderr": "startup for container '112' failed", "stderr_lines": ["startup for container '112' failed"], "stdout": "run_buffer: 571 Script exited with status 2\nlxc_init: 845 Failed to run lxc.hook.pre-start for container \"112\"\n__lxc_start: 2034 Failed to initialize container \"112\"", "stdout_lines": ["run_buffer: 571 Script exited with status 2", "lxc_init: 845 Failed to run lxc.hook.pre-start for container \"112\"", "__lxc_start: 2034 Failed to initialize container \"112\""]}
2025-07-18 15:12:25,876 p=123123 u=bill n=ansible INFO| fatal: [wg]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.104\". Make sure this host can be reached over ssh: Use of this system is private. If you are not authorized, disconnect immediately.\nFailure to comply will result in your destruction.hal@192.168.86.104: Permission denied (publickey).\r\n", "unreachable": true}
2025-07-18 15:12:27,670 p=123123 u=bill n=ansible INFO| fatal: [sonarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.66\". Make sure this host can be reached over ssh: Use of this system is private. If you are not authorized, disconnect immediately.\nFailure to comply will result in your destruction.hal@192.168.86.66: Permission denied (publickey).\r\n", "unreachable": true}
2025-07-18 15:12:28,729 p=123123 u=bill n=ansible INFO| fatal: [prowlarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.123\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.123 port 22: No route to host\r\n", "unreachable": true}
2025-07-18 15:12:28,796 p=123123 u=bill n=ansible INFO| fatal: [samsung]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.94\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.94 port 22: No route to host\r\n", "unreachable": true}
2025-07-18 15:12:29,000 p=123123 u=bill n=ansible INFO| fatal: [dell]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.55\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.55 port 22: No route to host\r\n", "unreachable": true}
2025-07-18 15:12:29,202 p=123123 u=bill n=ansible INFO| fatal: [maintainerr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.65\". Make sure this host can be reached over ssh: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\n@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\nIT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!\r\nSomeone could be eavesdropping on you right now (man-in-the-middle attack)!\r\nIt is also possible that a host key has just been changed.\r\nThe fingerprint for the ED25519 key sent by the remote host is\nSHA256:U1zJq/odIZDuR6itrbQYSul32AUl2r4DmB+7nesWJEY.\r\nPlease contact your system administrator.\r\nAdd correct host key in /home/bill/.ssh/known_hosts to get rid of this message.\r\nOffending ED25519 key in /home/bill/.ssh/known_hosts:21\r\n  remove with:\r\n  ssh-keygen -f '/home/bill/.ssh/known_hosts' -R '192.168.86.65'\r\nAgent forwarding is disabled to avoid man-in-the-middle attacks.\r\nUpdateHostkeys is disabled because the host key is not trusted.\r\nUse of this system is private. If you are not authorized, disconnect immediately.\nFailure to comply will result in your destruction.hal@192.168.86.65: Permission denied (publickey).\r\n", "unreachable": true}
2025-07-18 15:12:33,132 p=123123 u=bill n=ansible INFO| fatal: [homeassistant]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@192.168.86.51: Permission denied (publickey).", "unreachable": true}
2025-07-18 15:12:34,038 p=123123 u=bill n=ansible INFO| fatal: [lily_laptop]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.53\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.53 port 22: No route to host\r\n", "unreachable": true}
2025-07-18 15:12:37,685 p=123123 u=bill n=ansible INFO| fatal: [paperless]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.96\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.96 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-18 15:12:48,286 p=123123 u=bill n=ansible INFO| fatal: [truenas]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/apt-get update", "msg": "", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "Package management tools are disabled on TrueNAS appliances.\n\nAttempting to update TrueNAS with apt or methods other than the TrueNAS web\ninterface can result in a nonfunctional system.\n", "stdout_lines": ["Package management tools are disabled on TrueNAS appliances.", "", "Attempting to update TrueNAS with apt or methods other than the TrueNAS web", "interface can result in a nonfunctional system."]}
2025-07-18 15:14:03,843 p=123123 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'str object' has no attribute 'home'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create user home directories\n  ^ here\n"}
2025-07-18 15:14:04,687 p=123123 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create NFS symlinks for lily\n  ^ here\n"}
2025-07-18 15:14:04,720 p=123123 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 51, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create local directories for lily\n  ^ here\n"}
2025-07-18 15:14:04,753 p=123123 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 62, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create NFS symlinks for loretta\n  ^ here\n"}
2025-07-18 15:14:04,786 p=123123 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 74, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create local directories for loretta\n  ^ here\n"}
2025-07-18 15:14:46,101 p=123123 u=bill n=ansible INFO| fatal: [trilium -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/104.conf to /etc/pve/lxc/104.conf.backup.1752866080", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_e1t9_yqn/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_e1t9_yqn/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/104.conf.backup.1752866080'\n"}
2025-07-18 15:14:46,127 p=123123 u=bill n=ansible INFO| fatal: [overseer -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/105.conf to /etc/pve/lxc/105.conf.backup.1752866081", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_sjoffmh1/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_sjoffmh1/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/105.conf.backup.1752866081'\n"}
2025-07-18 15:14:46,162 p=123123 u=bill n=ansible INFO| fatal: [photoprism -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/103.conf to /etc/pve/lxc/103.conf.backup.1752866080", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_s5qfeixp/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_s5qfeixp/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/103.conf.backup.1752866080'\n"}
2025-07-18 15:14:46,199 p=123123 u=bill n=ansible INFO| fatal: [bazarr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/111.conf to /etc/pve/lxc/111.conf.backup.1752866080", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_bn4u3txn/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_bn4u3txn/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/111.conf.backup.1752866080'\n"}
2025-07-18 15:14:46,251 p=123123 u=bill n=ansible INFO| fatal: [books -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/109.conf to /etc/pve/lxc/109.conf.backup.1752866081", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_iao8fdn4/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_iao8fdn4/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/109.conf.backup.1752866081'\n"}
2025-07-18 15:14:46,381 p=123123 u=bill n=ansible INFO| fatal: [radarr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/106.conf to /etc/pve/lxc/106.conf.backup.1752866081", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_xf_vyxbr/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_xf_vyxbr/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/106.conf.backup.1752866081'\n"}
2025-07-18 15:14:46,449 p=123123 u=bill n=ansible INFO| fatal: [sab -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/116.conf to /etc/pve/lxc/116.conf.backup.1752866081", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_crvot5fe/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_crvot5fe/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/116.conf.backup.1752866081'\n"}
2025-07-18 15:14:46,452 p=123123 u=bill n=ansible INFO| fatal: [ntfy -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/113.conf to /etc/pve/lxc/113.conf.backup.1752866081", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_ngqsxvf3/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_ngqsxvf3/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/113.conf.backup.1752866081'\n"}
2025-07-18 15:14:46,479 p=123123 u=bill n=ansible INFO| fatal: [tautulli -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/110.conf to /etc/pve/lxc/110.conf.backup.1752866081", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_90edwrqe/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_90edwrqe/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/110.conf.backup.1752866081'\n"}
2025-07-18 15:14:46,496 p=123123 u=bill n=ansible INFO| fatal: [cloudflared -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/102.conf to /etc/pve/lxc/102.conf.backup.1752866081", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_07g8c8vl/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_07g8c8vl/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/102.conf.backup.1752866081'\n"}
2025-07-18 15:14:46,613 p=123123 u=bill n=ansible INFO| fatal: [homepage -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/114.conf to /etc/pve/lxc/114.conf.backup.1752866081", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_su4b2lyn/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_su4b2lyn/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/114.conf.backup.1752866081'\n"}
2025-07-18 15:14:46,676 p=123123 u=bill n=ansible INFO| fatal: [calibre-web -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/115.conf to /etc/pve/lxc/115.conf.backup.1752866082", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_kgamaxxu/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_kgamaxxu/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/115.conf.backup.1752866082'\n"}
2025-07-18 15:15:59,784 p=123123 u=bill n=ansible INFO| fatal: [windows11]: FAILED! => {"msg": "The field 'password' has an invalid value, which includes an undefined variable.. 'windows_password' is undefined"}
2025-07-18 15:21:17,494 p=131158 u=bill n=ansible INFO| fatal: [paperless]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.96\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.96 port 22: No route to host\r\n", "unreachable": true}
2025-07-18 15:22:29,424 p=131329 u=bill n=ansible INFO| fatal: [paperless -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/112.conf to /etc/pve/lxc/112.conf.backup.1752866547", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_f570b8h3/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_f570b8h3/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/112.conf.backup.1752866547'\n"}
2025-07-18 15:34:37,661 p=132212 u=bill n=ansible INFO| wg | UNREACHABLE! => {
2025-07-18 15:34:38,601 p=132212 u=bill n=ansible INFO| sonarr | UNREACHABLE! => {
2025-07-18 15:34:39,691 p=132212 u=bill n=ansible INFO| maintainerr | UNREACHABLE! => {
2025-07-18 15:34:40,514 p=132212 u=bill n=ansible INFO| samsung | UNREACHABLE! => {
2025-07-18 15:34:40,528 p=132212 u=bill n=ansible INFO| prowlarr | UNREACHABLE! => {
2025-07-18 15:34:40,826 p=132212 u=bill n=ansible INFO| dell | UNREACHABLE! => {
2025-07-18 15:34:41,325 p=132212 u=bill n=ansible INFO| windows11 | FAILED! => {
2025-07-18 15:34:41,337 p=132212 u=bill n=ansible INFO| homeassistant | UNREACHABLE! => {
2025-07-18 15:34:43,700 p=132212 u=bill n=ansible INFO| lily_laptop | UNREACHABLE! => {
2025-07-18 15:38:09,611 p=132684 u=bill n=ansible INFO| sonarr | UNREACHABLE! => {
2025-07-18 15:38:09,613 p=132684 u=bill n=ansible INFO| wg | UNREACHABLE! => {
2025-07-18 15:44:30,013 p=133100 u=bill n=ansible INFO| fatal: [sonarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.66\". Make sure this host can be reached over ssh: Use of this system is private. If you are not authorized, disconnect immediately.\nFailure to comply will result in your destruction.hal@192.168.86.66: Permission denied (publickey).\r\n", "unreachable": true}
2025-07-18 15:46:53,606 p=133246 u=bill n=ansible INFO| fatal: [sonarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.66\". Make sure this host can be reached over ssh: Use of this system is private. If you are not authorized, disconnect immediately.\nFailure to comply will result in your destruction.hal@192.168.86.66: Permission denied (publickey).\r\n", "unreachable": true}
2025-07-18 16:19:35,568 p=134846 u=bill n=ansible INFO| fatal: [truenas]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/apt-get update", "msg": "", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "Package management tools are disabled on TrueNAS appliances.\n\nAttempting to update TrueNAS with apt or methods other than the TrueNAS web\ninterface can result in a nonfunctional system.\n", "stdout_lines": ["Package management tools are disabled on TrueNAS appliances.", "", "Attempting to update TrueNAS with apt or methods other than the TrueNAS web", "interface can result in a nonfunctional system."]}
2025-07-18 16:20:52,040 p=134899 u=bill n=ansible INFO| fatal: [truenas]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.109\". Make sure this host can be reached over ssh: hal@192.168.86.109: Permission denied (publickey).\r\n", "unreachable": true}
2025-07-18 16:26:48,722 p=135402 u=bill n=ansible INFO| homeassistant | UNREACHABLE! => {
2025-07-18 16:29:59,053 p=135564 u=bill n=ansible INFO| maintainerr | UNREACHABLE! => {
2025-07-18 16:29:59,228 p=135564 u=bill n=ansible INFO| prowlarr | UNREACHABLE! => {
2025-07-18 16:29:59,753 p=135564 u=bill n=ansible INFO| samsung | UNREACHABLE! => {
2025-07-18 16:29:59,820 p=135564 u=bill n=ansible INFO| dell | UNREACHABLE! => {
2025-07-18 16:30:00,457 p=135564 u=bill n=ansible INFO| windows11 | FAILED! => {
2025-07-18 16:30:00,589 p=135564 u=bill n=ansible INFO| homeassistant | UNREACHABLE! => {
2025-07-18 16:30:02,869 p=135564 u=bill n=ansible INFO| lily_laptop | UNREACHABLE! => {
2025-07-18 17:02:13,307 p=137843 u=bill n=ansible INFO| fatal: [ha]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
2025-07-18 17:02:36,680 p=137901 u=bill n=ansible INFO| fatal: [ha]: FAILED! => {"msg": "'vault_bill_ssh_keys' is undefined"}
2025-07-18 17:05:22,937 p=140168 u=bill n=ansible INFO| samsung | UNREACHABLE! => {
2025-07-18 17:05:22,946 p=140168 u=bill n=ansible INFO| prowlarr | UNREACHABLE! => {
2025-07-18 17:05:23,387 p=140168 u=bill n=ansible INFO| dell | UNREACHABLE! => {
2025-07-18 17:05:23,889 p=140168 u=bill n=ansible INFO| windows11 | FAILED! => {
2025-07-18 17:05:26,261 p=140168 u=bill n=ansible INFO| lily_laptop | UNREACHABLE! => {
2025-07-19 12:21:19,053 p=149246 u=bill n=ansible INFO| books | FAILED! => {
2025-07-19 12:51:19,190 p=149751 u=bill n=ansible INFO| books | FAILED! => {
2025-07-19 13:43:15,528 p=152190 u=bill n=ansible INFO| fatal: [desktop]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.40\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.40 port 22: No route to host\r\n", "unreachable": true}
2025-07-19 13:43:15,537 p=152190 u=bill n=ansible INFO| fatal: [prowlarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.123\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.123 port 22: No route to host\r\n", "unreachable": true}
2025-07-19 13:43:16,446 p=152190 u=bill n=ansible INFO| fatal: [samsung]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.94\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.94 port 22: No route to host\r\n", "unreachable": true}
2025-07-19 13:43:21,077 p=152190 u=bill n=ansible INFO| fatal: [lily_laptop]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.53\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.53 port 22: No route to host\r\n", "unreachable": true}
2025-07-19 13:45:49,572 p=152190 u=bill n=ansible INFO| fatal: [dell]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'str object' has no attribute 'home'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create user home directories\n  ^ here\n"}
2025-07-19 13:45:51,209 p=152190 u=bill n=ansible INFO| fatal: [dell]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create NFS symlinks for lily\n  ^ here\n"}
2025-07-19 13:45:51,245 p=152190 u=bill n=ansible INFO| fatal: [dell]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 51, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create local directories for lily\n  ^ here\n"}
2025-07-19 13:45:51,274 p=152190 u=bill n=ansible INFO| fatal: [dell]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 62, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create NFS symlinks for loretta\n  ^ here\n"}
2025-07-19 13:45:51,304 p=152190 u=bill n=ansible INFO| fatal: [dell]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 74, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create local directories for loretta\n  ^ here\n"}
2025-07-19 13:46:07,931 p=152190 u=bill n=ansible INFO| fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service sshd: host"}
2025-07-19 13:46:42,047 p=152190 u=bill n=ansible INFO| fatal: [wg -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/101.conf to /etc/pve/lxc/101.conf.backup.1752947194", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_dzdsskv_/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_dzdsskv_/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/101.conf.backup.1752947194'\n"}
2025-07-19 13:46:42,097 p=152190 u=bill n=ansible INFO| fatal: [photoprism -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/103.conf to /etc/pve/lxc/103.conf.backup.1752947194", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_f43sre4_/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_f43sre4_/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/103.conf.backup.1752947194'\n"}
2025-07-19 13:46:42,149 p=152190 u=bill n=ansible INFO| fatal: [trilium -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/104.conf to /etc/pve/lxc/104.conf.backup.1752947194", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_51_fl15b/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_51_fl15b/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/104.conf.backup.1752947194'\n"}
2025-07-19 13:46:42,180 p=152190 u=bill n=ansible INFO| fatal: [bazarr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/111.conf to /etc/pve/lxc/111.conf.backup.1752947194", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_0mxrdam4/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_0mxrdam4/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/111.conf.backup.1752947194'\n"}
2025-07-19 13:46:42,205 p=152190 u=bill n=ansible INFO| fatal: [sonarr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/107.conf to /etc/pve/lxc/107.conf.backup.1752947194", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_znv8jqki/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_znv8jqki/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/107.conf.backup.1752947194'\n"}
2025-07-19 13:46:42,290 p=152190 u=bill n=ansible INFO| fatal: [paperless -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/112.conf to /etc/pve/lxc/112.conf.backup.1752947195", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_k76_qnih/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_k76_qnih/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/112.conf.backup.1752947195'\n"}
2025-07-19 13:46:42,358 p=152190 u=bill n=ansible INFO| fatal: [books -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/109.conf to /etc/pve/lxc/109.conf.backup.1752947195", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_d6ots2hc/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_d6ots2hc/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/109.conf.backup.1752947195'\n"}
2025-07-19 13:46:42,418 p=152190 u=bill n=ansible INFO| fatal: [overseer -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/105.conf to /etc/pve/lxc/105.conf.backup.1752947195", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_16_4vwpj/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_16_4vwpj/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/105.conf.backup.1752947195'\n"}
2025-07-19 13:46:42,460 p=152190 u=bill n=ansible INFO| fatal: [radarr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/106.conf to /etc/pve/lxc/106.conf.backup.1752947195", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_hnuqxrtm/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_hnuqxrtm/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/106.conf.backup.1752947195'\n"}
2025-07-19 13:46:42,497 p=152190 u=bill n=ansible INFO| fatal: [ntfy -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/113.conf to /etc/pve/lxc/113.conf.backup.1752947195", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_yho4mlzd/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_yho4mlzd/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/113.conf.backup.1752947195'\n"}
2025-07-19 13:46:42,526 p=152190 u=bill n=ansible INFO| fatal: [maintainerr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/108.conf to /etc/pve/lxc/108.conf.backup.1752947196", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_az3d8i7h/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_az3d8i7h/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/108.conf.backup.1752947196'\n"}
2025-07-19 13:46:42,597 p=152190 u=bill n=ansible INFO| fatal: [sab -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/116.conf to /etc/pve/lxc/116.conf.backup.1752947197", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_nz4r9vf2/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_nz4r9vf2/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/116.conf.backup.1752947197'\n"}
2025-07-19 13:46:42,681 p=152190 u=bill n=ansible INFO| fatal: [tautulli -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/110.conf to /etc/pve/lxc/110.conf.backup.1752947196", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_zd_cq_ig/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_zd_cq_ig/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/110.conf.backup.1752947196'\n"}
2025-07-19 13:46:42,720 p=152190 u=bill n=ansible INFO| fatal: [cloudflared -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/102.conf to /etc/pve/lxc/102.conf.backup.1752947197", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_vr_s3p5a/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_vr_s3p5a/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/102.conf.backup.1752947197'\n"}
2025-07-19 13:46:42,742 p=152190 u=bill n=ansible INFO| fatal: [homepage -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/114.conf to /etc/pve/lxc/114.conf.backup.1752947196", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_sl4dszdz/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_sl4dszdz/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/114.conf.backup.1752947196'\n"}
2025-07-19 13:46:42,765 p=152190 u=bill n=ansible INFO| fatal: [calibre-web -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/115.conf to /etc/pve/lxc/115.conf.backup.1752947197", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_wsebq90q/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_wsebq90q/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/115.conf.backup.1752947197'\n"}
2025-07-19 13:48:14,512 p=152190 u=bill n=ansible INFO| fatal: [windows11]: FAILED! => {"msg": "The field 'password' has an invalid value, which includes an undefined variable.. 'windows_password' is undefined"}
