ERROR! Could not read vault password file /home/bill/.vault_pass.txt: [Errno 13] Permission denied: '/home/bill/.vault_pass.txt'
2025-07-19 14:24:01,849 p=164496 u=bill n=ansible INFO| fatal: [prowlarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.123\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.123 port 22: No route to host\r\n", "unreachable": true}
2025-07-19 14:24:01,854 p=164496 u=bill n=ansible INFO| fatal: [desktop]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.40\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.40 port 22: No route to host\r\n", "unreachable": true}
2025-07-19 14:24:01,923 p=164496 u=bill n=ansible INFO| fatal: [samsung]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.94\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.94 port 22: No route to host\r\n", "unreachable": true}
2025-07-19 14:24:07,221 p=164496 u=bill n=ansible INFO| fatal: [lily_laptop]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.53\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.53 port 22: No route to host\r\n", "unreachable": true}
2025-07-19 14:26:17,952 p=164496 u=bill n=ansible INFO| fatal: [dell]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'str object' has no attribute 'home'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create user home directories\n  ^ here\n"}
2025-07-19 14:26:19,516 p=164496 u=bill n=ansible INFO| fatal: [dell]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create NFS symlinks for lily\n  ^ here\n"}
2025-07-19 14:26:19,546 p=164496 u=bill n=ansible INFO| fatal: [dell]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 51, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create local directories for lily\n  ^ here\n"}
2025-07-19 14:26:19,578 p=164496 u=bill n=ansible INFO| fatal: [dell]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 62, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create NFS symlinks for loretta\n  ^ here\n"}
2025-07-19 14:26:19,606 p=164496 u=bill n=ansible INFO| fatal: [dell]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0): 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 74, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create local directories for loretta\n  ^ here\n"}
2025-07-19 14:26:37,449 p=164496 u=bill n=ansible INFO| fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service sshd: host"}
2025-07-19 14:27:10,981 p=164496 u=bill n=ansible INFO| fatal: [wg -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/101.conf to /etc/pve/lxc/101.conf.backup.1752949623", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_5btjpl3d/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_5btjpl3d/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/101.conf.backup.1752949623'\n"}
2025-07-19 14:27:11,012 p=164496 u=bill n=ansible INFO| fatal: [photoprism -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/103.conf to /etc/pve/lxc/103.conf.backup.1752949623", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_vkwgai8c/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_vkwgai8c/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/103.conf.backup.1752949623'\n"}
2025-07-19 14:27:11,067 p=164496 u=bill n=ansible INFO| fatal: [bazarr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/111.conf to /etc/pve/lxc/111.conf.backup.1752949623", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_2qastrtl/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_2qastrtl/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/111.conf.backup.1752949623'\n"}
2025-07-19 14:27:11,110 p=164496 u=bill n=ansible INFO| fatal: [trilium -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/104.conf to /etc/pve/lxc/104.conf.backup.1752949623", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_7nnstelx/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_7nnstelx/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/104.conf.backup.1752949623'\n"}
2025-07-19 14:27:11,139 p=164496 u=bill n=ansible INFO| fatal: [sonarr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/107.conf to /etc/pve/lxc/107.conf.backup.1752949623", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_0pnn6ify/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_0pnn6ify/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/107.conf.backup.1752949623'\n"}
2025-07-19 14:27:11,233 p=164496 u=bill n=ansible INFO| fatal: [paperless -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/112.conf to /etc/pve/lxc/112.conf.backup.1752949624", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_81wuyyiw/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_81wuyyiw/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/112.conf.backup.1752949624'\n"}
2025-07-19 14:27:11,279 p=164496 u=bill n=ansible INFO| fatal: [books -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/109.conf to /etc/pve/lxc/109.conf.backup.1752949624", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_z2qqfzyz/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_z2qqfzyz/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/109.conf.backup.1752949624'\n"}
2025-07-19 14:27:11,343 p=164496 u=bill n=ansible INFO| fatal: [overseer -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/105.conf to /etc/pve/lxc/105.conf.backup.1752949624", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_mgoufejp/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_mgoufejp/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/105.conf.backup.1752949624'\n"}
2025-07-19 14:27:11,366 p=164496 u=bill n=ansible INFO| fatal: [radarr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/106.conf to /etc/pve/lxc/106.conf.backup.1752949624", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_0uz401fj/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_0uz401fj/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/106.conf.backup.1752949624'\n"}
2025-07-19 14:27:11,403 p=164496 u=bill n=ansible INFO| fatal: [ntfy -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/113.conf to /etc/pve/lxc/113.conf.backup.1752949624", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_1_rph764/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_1_rph764/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/113.conf.backup.1752949624'\n"}
2025-07-19 14:27:11,480 p=164496 u=bill n=ansible INFO| fatal: [maintainerr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/108.conf to /etc/pve/lxc/108.conf.backup.1752949625", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_qno4uy1q/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_qno4uy1q/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/108.conf.backup.1752949625'\n"}
2025-07-19 14:27:11,509 p=164496 u=bill n=ansible INFO| fatal: [sab -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/116.conf to /etc/pve/lxc/116.conf.backup.1752949625", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_67fvngec/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_67fvngec/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/116.conf.backup.1752949625'\n"}
2025-07-19 14:27:11,598 p=164496 u=bill n=ansible INFO| fatal: [tautulli -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/110.conf to /etc/pve/lxc/110.conf.backup.1752949625", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_vao4h4s6/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_vao4h4s6/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/110.conf.backup.1752949625'\n"}
2025-07-19 14:27:11,632 p=164496 u=bill n=ansible INFO| fatal: [cloudflared -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/102.conf to /etc/pve/lxc/102.conf.backup.1752949625", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_k_x76e9x/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_k_x76e9x/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/102.conf.backup.1752949625'\n"}
2025-07-19 14:27:11,640 p=164496 u=bill n=ansible INFO| fatal: [homepage -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/114.conf to /etc/pve/lxc/114.conf.backup.1752949625", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_50mw7wfe/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_50mw7wfe/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/114.conf.backup.1752949625'\n"}
2025-07-19 14:27:11,691 p=164496 u=bill n=ansible INFO| fatal: [calibre-web -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/115.conf to /etc/pve/lxc/115.conf.backup.1752949626", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_5uv_h526/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_5uv_h526/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/115.conf.backup.1752949626'\n"}
2025-07-19 14:28:41,222 p=164496 u=bill n=ansible INFO| fatal: [windows11]: FAILED! => {"msg": "The field 'password' has an invalid value, which includes an undefined variable.. 'windows_password' is undefined"}
