2025-07-21 11:23:22,748 p=13796 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"changed": false, "msg": "Failed to update apt cache after 5 retries: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: https://packages.microsoft.com/repos/code stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF, E:The repository 'https://packages.microsoft.com/repos/code stable InRelease' is not signed."}
2025-07-21 11:23:48,115 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "'group_definitions' is undefined"}
2025-07-21 11:23:50,554 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "'nfs_mounts' is undefined"}
2025-07-21 11:23:50,565 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "'nfs_mounts' is undefined"}
2025-07-21 11:23:50,577 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'nfs_mounts' is undefined\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/fstab_new.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add NFS mounts to fstab\n  ^ here\n"}
2025-07-21 11:23:50,587 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "'shared_mount_points' is undefined"}
2025-07-21 11:23:50,909 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "'nfs_mounts' is undefined"}
2025-07-21 11:23:50,920 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "'dict object' has no attribute 'results'"}
2025-07-21 11:23:50,949 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "'workstation_users' is undefined"}
2025-07-21 11:23:52,458 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0): 'workstation_users' is undefined\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create NFS symlinks for lily\n  ^ here\n"}
2025-07-21 11:23:52,478 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'lily') | list | length > 0): 'workstation_users' is undefined\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 51, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create local directories for lily\n  ^ here\n"}
2025-07-21 11:23:52,498 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0): 'workstation_users' is undefined\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 62, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create NFS symlinks for loretta\n  ^ here\n"}
2025-07-21 11:23:52,521 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "The conditional check 'workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0' failed. The error was: error while evaluating conditional (workstation_users | selectattr('name', 'equalto', 'loretta') | list | length > 0): 'workstation_users' is undefined\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 74, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create local directories for loretta\n  ^ here\n"}
2025-07-21 11:23:52,560 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "'users' is undefined"}
2025-07-21 11:24:28,042 p=13900 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"changed": false, "msg": "Failed to update apt cache after 5 retries: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: https://packages.microsoft.com/repos/code stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF, E:The repository 'https://packages.microsoft.com/repos/code stable InRelease' is not signed."}
2025-07-21 11:36:17,689 p=15137 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"changed": false, "msg": "Failed to update apt cache after 5 retries: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: https://packages.microsoft.com/repos/code stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF, E:The repository 'https://packages.microsoft.com/repos/code stable InRelease' is not signed."}
2025-07-21 11:38:42,111 p=15255 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"changed": false, "msg": "Failed to update apt cache after 5 retries: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: https://packages.microsoft.com/repos/code stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF, E:The repository 'https://packages.microsoft.com/repos/code stable InRelease' is not signed."}
2025-07-21 11:39:08,182 p=15255 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'dict object' has no attribute 'home'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create user home directories\n  ^ here\n"}
2025-07-21 11:39:12,322 p=15255 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "[{'username': 'bill', 'groups': ['bill', 'media', 'docs', 'data', 'adm', 'sudo', 'lily', 'loretta'], 'uid': 1000, 'shell': '/bin/bash', 'sudo': True, 'state': 'present', 'comment': 'Bill Knight', 'password': '{{ bill_password }}', 'ssh_keys': '{{ vault_bill_ssh_keys }}'}, {'username': 'hal', 'groups': ['ansible'], 'uid': 1999, 'shell': '/bin/bash', 'sudo': True, 'state': 'present', 'comment': 'Ansible System User', 'ssh_keys': '{{ vault_hal_ssh_key }}'}, {'username': 'loretta', 'groups': ['loretta', 'media', 'docs', 'data'], 'uid': 1003, 'shell': '/bin/bash', 'sudo': True, 'state': 'present', 'comment': 'Loretta Knight', 'password': '{{ vault_loretta_password }}'}, {'username': 'lily', 'groups': ['lily', 'media', 'docs', 'data'], 'uid': 1002, 'shell': '/bin/bash', 'sudo': True, 'state': 'present', 'comment': 'Lily Knight', 'password': '{{ vault_lily_password }}'}]: {{ vault_bill_password }}: 'vault_bill_password' is undefined"}
2025-07-21 11:41:48,365 p=15255 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"attempts": 3, "changed": false, "msg": "Failed to update apt cache after 5 retries: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: https://packages.microsoft.com/repos/code stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF, E:The repository 'https://packages.microsoft.com/repos/code stable InRelease' is not signed."}
2025-07-21 11:53:58,938 p=16097 u=bill n=ansible INFO| fatal: [prowlarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.123\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.123 port 22: No route to host\r\n", "unreachable": true}
2025-07-21 11:53:59,904 p=16097 u=bill n=ansible INFO| fatal: [dell]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.55\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.55 port 22: No route to host\r\n", "unreachable": true}
2025-07-21 12:02:37,465 p=21183 u=bill n=ansible INFO| fatal: [prowlarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.123\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.123 port 22: No route to host\r\n", "unreachable": true}
2025-07-21 12:02:38,422 p=21183 u=bill n=ansible INFO| fatal: [dell]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.55\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.55 port 22: No route to host\r\n", "unreachable": true}
2025-07-21 12:04:55,974 p=21183 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'dict object' has no attribute 'home'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create user home directories\n  ^ here\n"}
2025-07-21 12:04:55,987 p=21183 u=bill n=ansible INFO| fatal: [samsung]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'dict object' has no attribute 'home'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create user home directories\n  ^ here\n"}
2025-07-21 12:04:55,996 p=21183 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'dict object' has no attribute 'home'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create user home directories\n  ^ here\n"}
2025-07-21 12:05:00,120 p=21183 u=bill n=ansible INFO| fatal: [lily_laptop]: FAILED! => {"msg": "[{'username': 'bill', 'groups': ['bill', 'media', 'docs', 'data', 'adm', 'sudo', 'lily', 'loretta'], 'uid': 1000, 'shell': '/bin/bash', 'sudo': True, 'state': 'present', 'comment': 'Bill Knight', 'password': '{{ bill_password }}', 'ssh_keys': '{{ vault_bill_ssh_keys }}'}, {'username': 'hal', 'groups': ['ansible'], 'uid': 1999, 'shell': '/bin/bash', 'sudo': True, 'state': 'present', 'comment': 'Ansible System User', 'ssh_keys': '{{ vault_hal_ssh_key }}'}, {'username': 'loretta', 'groups': ['loretta', 'media', 'docs', 'data'], 'uid': 1003, 'shell': '/bin/bash', 'sudo': True, 'state': 'present', 'comment': 'Loretta Knight', 'password': '{{ vault_loretta_password }}'}, {'username': 'lily', 'groups': ['lily', 'media', 'docs', 'data'], 'uid': 1002, 'shell': '/bin/bash', 'sudo': True, 'state': 'present', 'comment': 'Lily Knight', 'password': '{{ vault_lily_password }}'}]: {{ vault_bill_password }}: 'vault_bill_password' is undefined"}
2025-07-21 12:05:18,486 p=21183 u=bill n=ansible INFO| fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service sshd: host"}
2025-07-21 12:05:52,007 p=21183 u=bill n=ansible INFO| fatal: [wg -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/101.conf to /etc/pve/lxc/101.conf.backup.1753113944", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_ypg053os/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_ypg053os/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/101.conf.backup.1753113944'\n"}
2025-07-21 12:05:52,096 p=21183 u=bill n=ansible INFO| fatal: [bazarr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/111.conf to /etc/pve/lxc/111.conf.backup.1753113944", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_ge1u8hy_/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_ge1u8hy_/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/111.conf.backup.1753113944'\n"}
2025-07-21 12:05:52,140 p=21183 u=bill n=ansible INFO| fatal: [trilium -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/104.conf to /etc/pve/lxc/104.conf.backup.1753113944", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload__mbbehet/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload__mbbehet/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/104.conf.backup.1753113944'\n"}
2025-07-21 12:05:52,169 p=21183 u=bill n=ansible INFO| fatal: [photoprism -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/103.conf to /etc/pve/lxc/103.conf.backup.1753113944", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_4rkj0oq7/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_4rkj0oq7/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/103.conf.backup.1753113944'\n"}
2025-07-21 12:05:52,191 p=21183 u=bill n=ansible INFO| fatal: [sonarr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/107.conf to /etc/pve/lxc/107.conf.backup.1753113944", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_oajn_1kr/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_oajn_1kr/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/107.conf.backup.1753113944'\n"}
2025-07-21 12:05:52,271 p=21183 u=bill n=ansible INFO| fatal: [paperless -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/112.conf to /etc/pve/lxc/112.conf.backup.1753113945", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_unyd834p/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_unyd834p/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/112.conf.backup.1753113945'\n"}
2025-07-21 12:05:52,374 p=21183 u=bill n=ansible INFO| fatal: [books -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/109.conf to /etc/pve/lxc/109.conf.backup.1753113946", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_te51ngqm/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_te51ngqm/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/109.conf.backup.1753113946'\n"}
2025-07-21 12:05:52,428 p=21183 u=bill n=ansible INFO| fatal: [overseer -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/105.conf to /etc/pve/lxc/105.conf.backup.1753113945", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_wydcaq89/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_wydcaq89/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/105.conf.backup.1753113945'\n"}
2025-07-21 12:05:52,498 p=21183 u=bill n=ansible INFO| fatal: [ntfy -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/113.conf to /etc/pve/lxc/113.conf.backup.1753113945", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_yh3kgzr4/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_yh3kgzr4/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/113.conf.backup.1753113945'\n"}
2025-07-21 12:05:52,534 p=21183 u=bill n=ansible INFO| fatal: [radarr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/106.conf to /etc/pve/lxc/106.conf.backup.1753113946", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_1d9jueg7/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_1d9jueg7/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/106.conf.backup.1753113946'\n"}
2025-07-21 12:05:52,566 p=21183 u=bill n=ansible INFO| fatal: [maintainerr -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/108.conf to /etc/pve/lxc/108.conf.backup.1753113946", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_hq7l01_4/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_hq7l01_4/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/108.conf.backup.1753113946'\n"}
2025-07-21 12:05:52,607 p=21183 u=bill n=ansible INFO| fatal: [sab -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/116.conf to /etc/pve/lxc/116.conf.backup.1753113946", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_dv__ayzx/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_dv__ayzx/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/116.conf.backup.1753113946'\n"}
2025-07-21 12:05:52,676 p=21183 u=bill n=ansible INFO| fatal: [tautulli -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/110.conf to /etc/pve/lxc/110.conf.backup.1753113947", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_9l7q0gp5/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_9l7q0gp5/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/110.conf.backup.1753113947'\n"}
2025-07-21 12:05:52,753 p=21183 u=bill n=ansible INFO| fatal: [cloudflared -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/102.conf to /etc/pve/lxc/102.conf.backup.1753113947", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_g6pguyww/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_g6pguyww/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/102.conf.backup.1753113947'\n"}
2025-07-21 12:05:52,771 p=21183 u=bill n=ansible INFO| fatal: [homepage -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/114.conf to /etc/pve/lxc/114.conf.backup.1753113947", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_akt38koa/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_akt38koa/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/114.conf.backup.1753113947'\n"}
2025-07-21 12:05:52,784 p=21183 u=bill n=ansible INFO| fatal: [calibre-web -> pve(192.168.86.143)]: FAILED! => {"changed": false, "msg": "failed to copy: /etc/pve/lxc/115.conf to /etc/pve/lxc/115.conf.backup.1753113947", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.copy_payload_c1getwr2/ansible_ansible.legacy.copy_payload.zip/ansible/modules/copy.py\", line 683, in main\n  File \"/tmp/ansible_ansible.legacy.copy_payload_c1getwr2/ansible_ansible.legacy.copy_payload.zip/ansible/module_utils/basic.py\", line 1691, in atomic_move\n    os.chmod(b_dest, S_IRWU_RWG_RWO & ~umask)\nPermissionError: [Errno 1] Operation not permitted: b'/etc/pve/lxc/115.conf.backup.1753113947'\n"}
2025-07-21 12:07:23,270 p=21183 u=bill n=ansible INFO| fatal: [windows11]: FAILED! => {"msg": "The field 'password' has an invalid value, which includes an undefined variable.. 'windows_password' is undefined"}
2025-07-21 12:22:34,198 p=31449 u=bill n=ansible INFO| fatal: [pve]: FAILED! => {"changed": false, "msg": "Couldn't authenticate user: root@pam to https://192.168.86.143:8006/api2/json/access/ticket"}
2025-07-21 12:34:38,614 p=32303 u=bill n=ansible INFO| fatal: [pve]: FAILED! => {"changed": false, "msg": "state is present but all of the following are missing: node, hostname"}
2025-07-21 12:35:29,755 p=32394 u=bill n=ansible INFO| fatal: [pve]: FAILED! => {"changed": false, "msg": "value of state must be one of: present, absent, stopped, started, restarted, template, got: current"}
2025-07-21 12:36:08,407 p=32437 u=bill n=ansible INFO| fatal: [pve]: FAILED! => {"changed": false, "msg": "state is present but all of the following are missing: hostname"}
2025-07-21 12:37:03,090 p=32577 u=bill n=ansible INFO| fatal: [pve]: FAILED! => {"changed": false, "msg": "Couldn't authenticate user: root@pam to https://192.168.86.143:8006/api2/json/access/ticket"}
2025-07-21 12:37:53,836 p=32772 u=bill n=ansible INFO| fatal: [pve]: FAILED! => {"changed": false, "msg": "state is present but all of the following are missing: hostname"}
2025-07-21 12:38:13,859 p=32812 u=bill n=ansible INFO| fatal: [pve]: FAILED! => {"changed": false, "msg": "argument 'vmid' is of type <class 'str'> and we were unable to convert to int: \"'None'\" cannot be converted to an int"}
2025-07-21 12:39:26,791 p=32867 u=bill n=ansible INFO| fatal: [pve]: FAILED! => {"changed": false, "msg": "An error occurred: 403 Forbidden: Permission check failed (/storage/local, Datastore.Audit|Datastore.AllocateSpace)"}
2025-07-21 12:45:52,304 p=33057 u=bill n=ansible INFO| fatal: [pve]: FAILED! => {"changed": false, "msg": "ostemplate local:vztmpl/ubuntu-24.10-standard_24.10-1_amd64.tar.zst does not exist on node pve and storage local.", "vmid": 117}
2025-07-21 12:48:16,026 p=33267 u=bill n=ansible INFO| fatal: [pve]: FAILED! => {"changed": false, "msg": "An error occurred: 'name'"}
2025-07-21 13:53:09,413 p=33808 u=bill n=ansible INFO| fatal: [truenas]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/apt-get update", "msg": "", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "Package management tools are disabled on TrueNAS appliances.\n\nAttempting to update TrueNAS with apt or methods other than the TrueNAS web\ninterface can result in a nonfunctional system.\n", "stdout_lines": ["Package management tools are disabled on TrueNAS appliances.", "", "Attempting to update TrueNAS with apt or methods other than the TrueNAS web", "interface can result in a nonfunctional system."]}
2025-07-21 13:54:17,023 p=33880 u=bill n=ansible INFO| fatal: [truenas]: FAILED! => {"changed": false, "msg": "There was an issue creating /usr/local/bin/pbs-backup as requested: [Errno 30] Read-only file system: b'/usr/local/bin/pbs-backup'", "path": "/usr/local/bin/pbs-backup"}
2025-07-21 13:55:08,252 p=33964 u=bill n=ansible INFO| fatal: [truenas]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'loop' is undefined\n\nThe error appears to be in '/home/bill/git/home.net/setup-truenas-pbs-backup-compatible.yml': line 161, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Create cron job for automated backups\n      ^ here\n"}
2025-07-22 15:02:20,952 p=52211 u=bill n=ansible INFO| fatal: [prowlarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.123\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.123 port 22: No route to host\r\n", "unreachable": true}
2025-07-22 15:02:27,886 p=52211 u=bill n=ansible INFO| fatal: [samsung]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.94\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.94 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-22 15:02:34,217 p=52211 u=bill n=ansible INFO| fatal: [lily_laptop]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.53\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.53 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-23 14:34:48,674 p=60650 u=bill n=ansible INFO| fatal: [prowlarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.123\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.123 port 22: No route to host\r\n", "unreachable": true}
2025-07-23 14:34:49,622 p=60650 u=bill n=ansible INFO| fatal: [samsung]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.94\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.94 port 22: No route to host\r\n", "unreachable": true}
2025-07-23 14:34:49,707 p=60650 u=bill n=ansible INFO| fatal: [dell]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.55\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.55 port 22: No route to host\r\n", "unreachable": true}
2025-07-23 14:34:54,099 p=60650 u=bill n=ansible INFO| fatal: [lily_laptop]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.53\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.53 port 22: No route to host\r\n", "unreachable": true}
2025-07-24 15:47:10,180 p=70466 u=bill n=ansible INFO| fatal: [bazarr]: FAILED! => {"changed": false, "msg": "Unable to start service ssh: Job for ssh.service failed because the control process exited with error code.\nSee \"systemctl status ssh.service\" and \"journalctl -xeu ssh.service\" for details.\n"}
2025-07-24 15:48:41,577 p=71186 u=bill n=ansible INFO| bazarr | UNREACHABLE! => {
2025-07-24 15:49:51,845 p=71303 u=bill n=ansible INFO| bazarr | UNREACHABLE! => {
2025-07-24 16:01:13,166 p=72131 u=bill n=ansible INFO| fatal: [bazarr]: FAILED! => {"changed": false, "msg": "Unable to start service ssh: Job for ssh.service failed because the control process exited with error code.\nSee \"systemctl status ssh.service\" and \"journalctl -xeu ssh.service\" for details.\n"}
2025-07-24 16:07:52,785 p=73216 u=bill n=ansible INFO| fatal: [bazarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.76\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.76 port 22: Connection refused\r\n", "unreachable": true}
2025-07-24 16:07:54,778 p=73216 u=bill n=ansible INFO| fatal: [samsung]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.94\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.94 port 22: No route to host\r\n", "unreachable": true}
2025-07-24 16:07:54,789 p=73216 u=bill n=ansible INFO| fatal: [prowlarr]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.123\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.123 port 22: No route to host\r\n", "unreachable": true}
2025-07-24 16:08:02,752 p=73216 u=bill n=ansible INFO| fatal: [dell]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.55\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.55 port 22: Connection timed out\r\n", "unreachable": true}
2025-07-24 16:08:03,412 p=73216 u=bill n=ansible INFO| fatal: [lily_laptop]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.53\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.53 port 22: No route to host\r\n", "unreachable": true}
2025-07-24 16:10:27,452 p=73216 u=bill n=ansible INFO| fatal: [desktop]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'dict object' has no attribute 'home'\n\nThe error appears to be in '/home/bill/git/home.net/roles/workstation/tasks/user_directories.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create user home directories\n  ^ here\n"}
2025-07-24 16:14:30,727 p=73216 u=bill n=ansible INFO| fatal: [windows11]: FAILED! => {"msg": "The field 'password' has an invalid value, which includes an undefined variable.. 'windows_password' is undefined"}
